image:
  file: .gitpod.Dockerfile
tasks:
- init: >-
    mkdir -p /workspace/kde/src &&
    cd /workspace/kde/src &&
    git clone https://invent.kde.org/sdk/kdesrc-build.git &&
    cd - &&
    ln --symbolic $PWD/kdesrc-buildrc ~/.config/ &&
    sudo sed -i.bak 's/^# *deb-src/deb-src/g' /etc/apt/sources.list &&
    sudo apt-get update &&
    sudo apt-get build-dep -y extra-cmake-modules kconfig &&
    sudo apt-get install -y qt6-l10n-tools qt6-tools-dev-tools qt6-base-dev &&
    kdesrc-build --initial-setup
  command: >-
    kdesrc-build --include-dependencies kate
